apiVersion: v2
appVersion: "1.0"
description: Divorce - Document Generator Service
name: div-dgs
version: 2.0.14
dependencies:
    - name: java
      version: 5.3.0
      repository: 'oci://hmctspublic.azurecr.io/helm'
